export const translationsConfig = {
  eng: {
    Main: 'Main',
    'Alon Alush': 'Alon Alush',
    Shows: 'Shows',
    Videos: 'Videos',
    'Contact Me': 'Contact Me',
    'Public relations': 'Public relations',
    WhatsApp: 'WhatsApp',
    TikTok: 'TikTok',
    YouTube: 'YouTube',
    Facebook: 'Facebook',
    'Comedy Stan-Up & Host': 'Comedy Stan-Up & Host',
    'More Info': 'More Info',
    'Copy Text': 'Copy Text',
    Download: 'Download',
    'PR Images': 'PR Images',
    'PR Text Content': 'PR Text Content',
    'about-1':
      'Tech geek and a stand-up artist who finds Humor in the office and in his personal life.',
    'about-2': 'Enjoys sharing funny stories from everyday life on the light side of them.',
    'about-3':
      'The show is suitable for corporate events, employees collaboration events, conferences, company events and birthdays.',
    'about-4': "Let's bring laugh at your next event.",
    'Corporate Stand-Up': 'Corporate Stand-Up',
    'Corporate Stand-Up TEXT':
      'A show that connects teams toghether with entertaiment and humorous way.',
    'Custom Theme Show': 'Custom Theme Show',
    'Custom Theme Show TEXT':
      'A humorous show about life, marriage, children and everything in between. the nature of the show can be adjusted.',
    'Family Events': 'Family Events',
    'Family Events TEXT': 'A personal stand-up about the family of the main guest of the event.',
    'Events Hosting': 'Events Hosting',
    'Events Hosting TEXT':
      'Creating interest for the audience and adjusting it according to the nature of the event.',
    Language: 'Language',
  },
  heb: {
    Main: 'ראשי',
    'Alon Alush': 'אלון אלוש',
    Shows: 'סוגי מופעים',
    Videos: 'סרטונים',
    'Contact Me': 'יצירת קשר',
    'Public relations': 'יחסי ציבור',
    WhatsApp: 'וואטסאפ',
    TikTok: 'טיקטוק',
    YouTube: 'יוטיוב',
    Facebook: 'פייסבוק',
    'Comedy Stan-Up & Host': 'סטנדאפיסט הייטקיסט מנחה',
    'More Info': 'מידע נוסף',
    'Copy Text': 'העתק תוכן',
    Download: 'הורדה',
    'PR Images': 'תמונות פירסומים להורדה',
    'PR Text Content': 'תוכן לפירסומים',
    'about-1': 'הייטקיסט וסטנדאפיסט שמוצא את הצחוק במשרד ובחייו האישיים.',
    'about-2': 'נהנה לשתף סיפורים מצחיקים מהחיים השגרתיים על הצד המצחיק שלהם.',
    'about-3': 'המופע מתאים לערבי גיבוש עובדים, ימי כיף, כנסים, אירועי חברה וימי הולדת.',
    'about-4': 'בואו נצחק ביחד באירוע הבא.',
    'Corporate Stand-Up': 'סטנדאפ וגיבוש עובדים',
    'Corporate Stand-Up TEXT': 'אירוע שמחבר צוותי עבודה בצורה מבדרת, קלילה והומוריסטית.',
    'Custom Theme Show': 'סטנדאפ אישי',
    'Custom Theme Show TEXT':
      '    מופע הומוריסטי על החיים, נישואים, ילדים ועל מה שבניהם, ניתן להתאים את אופי המופע לפי    דרישות מראש.',
    'Family Events': 'סטנדאפ לאירוע משפחתי',
    'Family Events TEXT': 'סטנדאפ אישי על המשפחה של בעל/ת האירוע נציף את המצחיק מהסיפורים האישיים.',
    'Events Hosting': 'הנחיית אירועים',
    'Events Hosting TEXT': 'יצירת עיניין לקהל והתאמה שלו לפי אופי האירוע והקהל.',
    Language: 'שפה',
  },
};
